[versions]
android-gradle-plugin = "8.12.2"
androidx-activity = "1.11.0"
androidx-window = "1.5.0"
capsule = "2.1.1-patch2"
jetbrains-compose = "1.9.3"
jetbrains-compose-hotReload = "1.1.0-alpha01"
jetbrains-androidx-navigation = "2.9.1"
jetbrains-compose-window-size = "1.9.0"
jetbrains-dokka = "2.1.0"
kotlin = "2.2.21"
spotless = "8.0.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "androidx-window" }
jetbrains-androidx-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-androidx-navigation" }
jetbrains-compose-ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "jetbrains-compose" }
jetbrains-compose-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "jetbrains-compose-window-size" }
gaze-capsule = { module = "com.mocharealm.gaze:capsule", version.ref = "capsule" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose" }
jetbrains-compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "jetbrains-compose-hotReload" }
jetbrains-dokka = { id = "org.jetbrains.dokka", version.ref = "jetbrains-dokka" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }